### PR TITLE
Feature/allow filter by to address

### PR DESCRIPTION
**Pull request by sergiogragera**

### CODE REVIEW

**Comment by gessnerfl** [comment]
@sergiogragera  thanks for your contribution. Will think about how this can be implemented a bit more generic. Filtering was on my list as well. The implementation currently is limited to the REST interface and i would like to have it in both REST API and Web UI.

**Comment by sergiogragera** [comment]
Hi, I recommend you to cherry-pick commit [a997410f7](https://github.com/gessnerfl/fake-smtp-server/pull/103/commits/a997410f729faf58495fe36cec0edc732ef44610) to main branch. This commit eliminates duplicate code and introduces a random email builder chaining for tests.

By other hand, I am building a new Angular UI client. Have you thought about this? The use of some reactive framework can introduce an improvement at this point.

**Comment by gessnerfl** [comment]
Will either cherry pick or adopt the PR in the branch to make sure the duplication gets removed.
In general I'm open for UI changes but the tool is considered as a simple tool for testing. Here I think thymeleaf is also a proper solution. Angular would require major changes in the build and would add a lot of additional complexity. On the other hand it would remove the need of maintaining multiple controllers on the server side.

**Comment by sergiogragera** [comment]
I totally agree with this.

**Pull request merged**
