### PR TITLE
Add access to emails through REST controller

### PR DESCRIPTION
**Pull request by baczus**
Hi,
I added a REST controller to access emails through it.
It could be useful in case of adding integration tests to the system where the SMTP server is used.
Getting emails through REST API is much more convenient than scraping the web page ;)

### CODE REVIEW

**Comment by smuda** [comment]
@baczus This is one of the features I thought was missing in fake-smtp-server and I had decided to make a PR for that as well, but you were faster than me... :-)

Even though I'm not a maintainer, one thing I'm missing in your PR is how this function is supposed to be used. Perhaps you could add a MD-file with the appropriate information? For example curl examples to:

- list all emails
- retrieve one specific email

**Comment by baczus** [comment]
@smuda Good point :+1: I've added a section to README with simple examples.
Unfortunately, I'm not fluent in English so feel free to correct/rephrase it :wink:

**Comment by gessnerfl** [comment]
@baczus I like the idea of adding a REST API to the project. Did you consider using open api for the documentation? This would allow you to generate clients and would also describe the data model

**Comment by baczus** [comment]
@gessnerfl I added a dependency to _springdoc-openapi-ui_  Thanks to it, **Swagger UI** is available at _localhost:5080/swagger-ui.html_
Additionally, I moved method [_getEmailAttachmentById_](https://github.com/gessnerfl/fake-smtp-server/pull/32/commits/503bd229c0dd281aa4f07f285a7a9cbb68d4bb94#diff-90327b981f312da69f5419e0c9e6cc60L74) to the _EmailRestController_.

**Review by gessnerfl — APPROVED** [review]
change looks good to me. Will integrate it into master and provide a release after a small test and some optimizations

**Comment by gessnerfl** [comment]
The change is now released with version 1.6.0. The release also includes the latest Spring Boot version as well as the update of all dependencies to their latest version.

**Pull request merged**
