### PR TITLE
"Clean timer" parameterization

### PR DESCRIPTION
**Pull request by vilherda**
parameterization of delays of the scheduled task responsible of stored emails deletion

### CODE REVIEW

**Comment by gottschd** [comment]
Not a reviewer, but +1 for this PR.

We are doing load testing and with this PR, we would be able to "garbage collect" emails more often to save memory.

**Review by gessnerfl — COMMENTED** [review]
Changes look good to me. Thanks @vilherda  for your contribution. Can you please add the configuration parameters to the documentation in README.md

**Review by gessnerfl — APPROVED** [review]

**Comment by gottschd** [comment]
Hi,

thinking about this a little bit more and since there is no (official) release yet, please allow me to share some thoughts.

Would it make sense to be more specific in the naming of the new fields `fixedDelay` and `initialDelay`.  

The thoughts here are:
* Although there are placed under the `persistence` configuration - would you know they are about the purging of the emails or that they are releated to `maxNumberEmails`?
* What if, in the future, other schedules parameters with the same semantics (initalDelay, fixedDelay) or any other parameter must be introduced under `persistence`?

What do you think?

Anyway, thank you for this PR.
 
---
Danny

**Comment by gessnerfl** [comment]
@gottschd @vilherda this is the proposed change: #529. This is the corresponding PR #530. Any feedback would be appreciated

**Comment by vilherda** [comment]
Yes, I agree. With this design and the conf. structure, regardless of the future features, this part of the conf. shouldn't collide or be ambiguous.

**Pull request merged**
